"""empty message

Revision ID: 52199bbc91fb
Revises: d8c28ee1d86c
Create Date: 2019-04-07 15:47:43.980868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52199bbc91fb'
down_revision = 'd8c28ee1d86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'level')
    # ### end Alembic commands ###
