"""empty message

Revision ID: 7e40b3cdc319
Revises: 3152f16f94cb
Create Date: 2019-04-05 22:44:09.048881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e40b3cdc319'
down_revision = '3152f16f94cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('seed_id', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'seed_id')
    # ### end Alembic commands ###
