"""empty message

Revision ID: d8c28ee1d86c
Revises: 8319e6706539
Create Date: 2019-04-06 14:33:43.887822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c28ee1d86c'
down_revision = '8319e6706539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'tree_id')
    op.add_column('trees', sa.Column('branch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'branch_id')
    op.add_column('branches', sa.Column('tree_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
