"""empty message

Revision ID: 3152f16f94cb
Revises: 
Create Date: 2019-04-05 16:36:14.448834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3152f16f94cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeds')
    # ### end Alembic commands ###
