"""empty message

Revision ID: 7118e5e3dc03
Revises: 52199bbc91fb
Create Date: 2019-04-14 15:32:49.839430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7118e5e3dc03'
down_revision = '52199bbc91fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('level_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'level_id')
    # ### end Alembic commands ###
