"""empty message

Revision ID: 8a1ba339d34c
Revises: bc703f360e41
Create Date: 2019-04-27 17:03:32.166804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1ba339d34c'
down_revision = 'bc703f360e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.drop_constraint('branches_tree_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'trees', ['tree_id'], ['id'])
    op.drop_column('branches', 'tree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('tree', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key('branches_tree_fkey', 'branches', 'trees', ['tree'], ['id'])
    op.drop_column('branches', 'tree_id')
    # ### end Alembic commands ###
