"""empty message

Revision ID: b26eb3dd335b
Revises: 7cdf86bcd6a1
Create Date: 2019-04-16 16:05:20.777478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26eb3dd335b'
down_revision = '7cdf86bcd6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('tree', sa.Integer(), nullable=True))
    op.drop_constraint('branches_tree_id_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'trees', ['tree'], ['id'])
    op.drop_column('branches', 'tree_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key('branches_tree_id_fkey', 'branches', 'trees', ['tree_id'], ['id'])
    op.drop_column('branches', 'tree')
    # ### end Alembic commands ###
